version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-dashboard:web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
